freebsd-regression-test-suite: use pydoc pager to report
This fixes a broken pipe error when trying to pipe the output
of a bricoler report command:

Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe